# Generated by Django 6.0.2 on 2026-03-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit Card"),
                    ("debit_card", "Debit Card"),
                    ("upi", "UPI"),
                    ("net_banking", "Net Banking"),
                ],
                default="credit_card",
                max_length=20,
            ),
        ),
    ]
