# Generated by Django 6.0.3 on 2026-03-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('digital', 'Digital Payment')], default='digital', max_length=20),
        ),
    ]
