# Generated by Django 6.0.2 on 2026-03-11 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="pet_photos/"
            ),
        ),
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("feeding", "Feeding"),
                            ("walk", "Walk"),
                            ("medication", "Medication"),
                            ("grooming", "Grooming"),
                            ("behavior", "Behavior"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField()),
                (
                    "logged_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to="pets.pet",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
