# Generated by Django 6.0.3 on 2026-04-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('hamster', 'Hamster'), ('fish', 'Fish'), ('other', 'Other')], default='dog', max_length=20),
        ),
    ]
