# Generated by Django 6.0.3 on 2026-04-11 06:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_pet_pet_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('checkup', 'Regular Checkup'), ('vaccination', 'Vaccination'), ('surgery', 'Surgery'), ('medication', 'Medication Start'), ('emergency', 'Emergency'), ('other', 'Other')], default='checkup', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('veterinarian_name', models.CharField(blank=True, max_length=100)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='pets.pet')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
